### ISSUE TITLE
ERROR in 01-CREATE-A-TORRENT-FILE

### ISSUE THREAD

**Issue by jo-neves** [No9/torrential#6]
Hello,

I've created the DIR and then the 2 files. When I run "torrent create xyz/ -o xyz.torrent", it returns the error "(node:17900) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead."

I'm on Windows 10 and I tested multiple times.

Screenshot:

![error](https://user-images.githubusercontent.com/29694171/36389426-f0dae0fe-1596-11e8-9755-299003caba4f.png)

**Comment by No9** [comment]
Thanks @joao-neves95 
That problem seems to be with the torrent project not with this workshopper
Would you mind opening the issue there please 
https://github.com/maxogden/torrent

**Comment by jo-neves** [comment]
Sure, no problem!
